export { default as Home } from './Home'
export { default as About } from './About'
export { default as Gear } from './Gear'
export { default as Projects } from './Projects'
export { default as MovingImages } from './MovingImages'
export { default as Thoughts } from './Thoughts'
export { default as BlogPost } from './BlogPost'
export { default as Contact } from './Contact'
